apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/denishelena/argocd.git
    targetRevision: HEAD
    path: ./argo-files/manifests/app1
   
  destination:
    server: prd-ti-vtex-eks-use1-4dr
    namespace: nginx1

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true