apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heliocentric-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/denishelena/argocd.git
    targetRevision: HEAD
    path: ./argo-files/manifests/app2
   
  destination:
    server: https://C2ED5CC8019AB1758902710D04CBE0C5.gr7.us-east-1.eks.amazonaws.com
    namespace: nginx2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true